2021-04-25 15:39:58,754 ERROR: Exception on /user/Dima [GET] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 79, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ilya-debian/PyBlog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ilya-debian/PyBlog/app/templates/base.html", line 39, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ilya-debian/PyBlog/app/templates/user.html", line 21, in block "content"
    {{ form.hidden_tag() }}
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-04-25 15:40:06,833 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:40:08,838 ERROR: Exception on /user/Dima [GET] [in /home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ilya-debian/PyBlog/app/routes.py", line 79, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/ilya-debian/PyBlog/app/templates/user.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "/home/ilya-debian/PyBlog/app/templates/base.html", line 39, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ilya-debian/PyBlog/app/templates/user.html", line 21, in block "content"
    {{ form.hidden_tag() }}
  File "/home/ilya-debian/PyBlog/env/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-04-25 15:41:14,788 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:43:26,458 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:44:24,389 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:46:47,644 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:47:41,708 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:48:49,514 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:56:34,418 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:57:16,107 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 15:59:24,749 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:01:26,334 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:05:00,640 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:07:34,906 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:10:31,911 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:11:44,584 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:12:43,450 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:13:10,015 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:14:42,662 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:17:11,631 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:21:28,788 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:22:58,041 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:24:38,560 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:26:13,292 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:27:32,195 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:28:00,318 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:34:25,676 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:36:11,935 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:40:32,638 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:41:59,175 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:45:28,958 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:46:05,851 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:47:02,999 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:49:14,679 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 16:59:59,519 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:01:23,824 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:02:17,514 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:07:49,904 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:08:40,534 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:10:24,167 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:16:19,654 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:19:07,287 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:24:13,307 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:31:23,970 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:32:05,993 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:34:22,195 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:34:36,793 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:44:38,148 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:46:39,113 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:47:05,675 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:47:30,922 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
2021-04-25 17:50:55,954 INFO: Microblog startup [in /home/ilya-debian/PyBlog/app/__init__.py:45]
